# ========================
# Spring Cloud Config
# ========================
spring.cloud.config.enabled=false

# ========================
# Base de datos PostgreSQL
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/practica1_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ========================
# JPA / Hibernate
# ========================
spring.jpa.open-in-view=false

# ========================
# Jackson (No responder campos nulos)
# ========================
spring.jackson.default-property-inclusion=non_null


# ========================
# Flyway
# ========================
spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public

# ========================
# GestoPago - Feign Client (Servidor Real)
# ========================
gestopago.auth.url=https://gestopago.portalventas.net

# GestoPago - Credenciales Reales
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.auth.refresh-rate-ms=3600000

# ========================
# Servidor
# ========================
server.port=8081

# ========================
# Servicio Productos (PuntoRed - SERVIDOR EXTERNO REAL)
# ========================
productos.service.url=https://gestopago.portalventas.net
productos.service.id-distribuidor=83
productos.service.codigo-dispositivo=GPS83-TPV-17
# Cron: ejecutar 1 vez al dia a las 6am (max 3 llamadas/dia segun documentacion PuntoRed)
productos.service.cron=0 0 6 * * *
